name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
          FIREBASE_PROJECT_ID: b-rational
        run: |
          echo "${{ secrets.GCP_SA_KEY_JSON }}" > "$GOOGLE_APPLICATION_CREDENTIALS"
          npx --yes firebase-tools@latest deploy --only hosting --project "$FIREBASE_PROJECT_ID"


